In [4]:
#import all important libraries
import pandas as pd
import numpy as np

In [5]:
crop = pd.read_csv(r"/Users/snehalsandipmane/AI-based-Crop-Reccomendation-System/Crop_recommendation.csv")
crop.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [6]:
crop.shape

(1200, 8)

In [7]:
crop.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            1200 non-null   int64
 1   P            1200 non-null   int64
 2   K            1200 non-null   int64
 3   temperature  1200 non-null   float64
 4   humidity     1200 non-null   float64
 5   ph           1200 non-null   float64
 6   rainfall     1200 non-null   float64
 7   label        1200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 75.1 KB

In [8]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [9]:
crop.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,64.865833,57.928333,64.105833,24.405231,72.052715,6.471832,113.093625
std,37.858582,39.170612,63.321660,4.786735,20.946371,0.705604,52.323312
min,0.000000,5.000000,5.000000,8.825675,14.258040,4.507524,40.126504
25%,29.000000,29.000000,25.000000,22.213055,61.906517,6.010318,75.110248
50%,73.000000,47.000000,40.000000,24.597716,80.544357,6.389200,99.524658
75%,97.000000,75.000000,60.000000,26.566480,84.476920,6.916851,122.440305
max,140.000000,145.000000,205.000000,41.948657,94.964199,8.868741,298.560117

In [10]:
print(crop.dtypes)

N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label              str
dtype: object

In [30]:
# crop.corr()

In [29]:
# List of expected numeric columns
numeric_columns = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']

# Convert each to numeric (invalid strings become NaN)
for col in numeric_columns:
    crop[col] = pd.to_numeric(crop[col], errors='coerce')

# Drop rows with NaN (e.g., where 'rice' was accidentally in a numeric column)
crop = crop.dropna()
#print(crop.corr())

In [13]:
crop.label.value_counts()

label
rice          100
maize         100
chickpea      100
banana        100
mango         100
grapes        100
watermelon    100
apple         100
orange        100
cotton        100
jute          100
coffee        100
Name: count, dtype: int64

In [14]:
crop['label'].unique().size

12

In [15]:
crop_dict = {
    'rice':1,        
    'maize':2,
    'jute':3,
    'cotton':4,
    'coconut':5,
    'papaya':6,
    'orange':7,
    'apple':8,
    'muskmelon':9,
    'watermelon':10,
    'grapes':11,
    'mango':12,
    'banana':13,
    'pomegranate':14,
    'lentil':15,
    'blackgram':16,
    'mungbean':17,
    'mothbeans':18,
    'pigeonpeas':19,
    'kidneybeans':20,
    'chickpea':21,
    'coffee':22        
}
crop['label'] = crop['label'].map(crop_dict)

In [16]:
crop

        N   P   K  temperature   humidity        ph    rainfall  label
0      90  42  43    20.879744  82.002744  6.502985  202.935536      1
1      85  58  41    21.770462  80.319644  7.038096  226.655537      1
2      60  55  44    23.004459  82.320763  7.840207  263.964248      1
3      74  35  40    26.491096  80.158363  6.980401  242.864034      1
4      78  42  42    20.130175  81.604873  7.628473  262.717340      1
...   ...  ..  ..          ...        ...       ...         ...    ...
1195  107  34  32    26.774637  66.413269  6.780064  177.774507     22
1196   99  15  27    27.417112  56.636362  6.086922  127.924610     22
1197  118  33  30    24.131797  67.225123  6.362608  173.322839     22
1198  117  32  34    26.272418  52.127394  6.758793  127.175293     22
1199  104  18  30    23.603016  60.396475  6.779833  140.937041     22

[1200 rows x 8 columns]

In [17]:
X = crop.drop('label',axis =1)
y = crop['label']

In [18]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: label, dtype: int64

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2,random_state=42)

In [20]:
from sklearn.preprocessing import MinMaxScaler
mx = MinMaxScaler()
X_train =  mx.fit_transform(X_train)
X_test = mx.transform(X_test)

In [21]:
X_train

array([[0.65714286, 0.54285714, 0.235     , ..., 0.83319377, 0.44341598,
        0.20979361],
       [0.21428571, 0.16428571, 0.125     , ..., 0.47029665, 0.12795025,
        0.22588754],
       [0.47857143, 0.3       , 0.195     , ..., 0.83716692, 0.7719304 ,
        0.93031697],
       ...,
       [0.7       , 0.15714286, 0.11      , ..., 0.4591156 , 0.62715056,
        0.60988194],
       [0.22142857, 0.14285714, 0.035     , ..., 0.93949123, 0.57624806,
        0.27742828],
       [0.61428571, 0.15      , 0.11      , ..., 0.47897934, 0.36142979,
        0.5896867 ]], shape=(960, 7))

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test=sc.transform(X_test)

In [23]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
randclf = RandomForestClassifier()
randclf.fit(X_train,y_train)
y_pred = randclf.predict(X_test)
accuracy_score(y_test,y_pred)

0.9875

In [24]:
crop.columns

Index(['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall', 'label'], dtype='str')

In [25]:
def recommendation(N,P,K,temperature,humidity,ph,rainfall):
    features = np.array([[N,P,K,temperature,humidity,ph,rainfall]])
    mx_features = mx.fit_transform(features)
    sc_mx_features=sc.fit_transform(mx_features)
    prediction = randclf.predict(sc_mx_features).reshape(1,-1)
    return prediction[0]

In [26]:
N = 90
P = 42
K = 43
temperature = 40.0 
humidity = 22
ph = 7
rainfall = 202
predict = recommendation(N,P,K,temperature,humidity,ph,rainfall)

In [27]:
crop.head(10)

    N   P   K  temperature   humidity        ph    rainfall  label
0  90  42  43    20.879744  82.002744  6.502985  202.935536      1
1  85  58  41    21.770462  80.319644  7.038096  226.655537      1
2  60  55  44    23.004459  82.320763  7.840207  263.964248      1
3  74  35  40    26.491096  80.158363  6.980401  242.864034      1
4  78  42  42    20.130175  81.604873  7.628473  262.717340      1
5  69  37  42    23.058049  83.370118  7.073454  251.055000      1
6  69  55  38    22.708838  82.639414  5.700806  271.324860      1
7  94  53  40    20.277744  82.894086  5.718627  241.974195      1
8  89  54  38    24.515881  83.535216  6.685346  230.446236      1
9  68  58  38    23.223974  83.033227  6.336254  221.209196      1

In [28]:
predict

array([3])